name: Continuous Integration

on:
  push:
    branches: main
  pull_request:

jobs:
  check-code:
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run check

  upload-preview-artifact:
    name: Upload preview artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci

      - name: Build package
        run: npm run package

      - uses: actions/upload-artifact@v3
        with:
          name: extension-preview-package
          path: ./web-ext-artifacts/accessibility_checker_for_github_markdown-0.0.0.zip
