name: CI Checks

on:
  push:
    branches: main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3

      - run: npm ci

      - name: Check code formatting
        run: npm run check:formatting

      - name: Check types
        run: npm run check:types

      - name: Package preview
        id: package
        run: |
          npm run package
          echo "zip_path=./web-ext-artifacts/accessibility_checker_for_github_markdown-${{github.ref_name}}.zip" >> "$GITHUB_OUTPUT"

      - uses: actions/upload-artifact@v3
        with:
          name: extension-preview-package
          path: ${{ steps.package.outputs.zip_path }}

